- points:
  - - 377
    - 142
  - - 380
    - 429
  - - 617
    - 429
  - - 703
    - 330
  - - 560
    - 142
  type: area
- points:
  - - 371
    - 141
  - - 373
    - 427
  - - 85
    - 430
  - - 13
    - 336
  - - 106
    - 145
  type: area
- points:
  - - 534
    - 109
  - - 753
    - 405
  type: wire
- points:
  - - 159
    - 106
  - - 20
    - 394
  type: wire
