- points:
  - - 200
    - 200
  - - 500
    - 180
  - - 600
    - 400
  - - 300
    - 300
  - - 100
    - 360
  type: area
- points:
  - - 300
    - 40
  - - 20
    - 400
  type: wire
- points:
  - - 440
    - 40
  - - 700
    - 400
  type: wire
